### ISSUE TITLE
Unknown format specifier "a" in class-woo-sidebars.php

### ISSUE THREAD

**Issue by SteveTro** [woocommerce/woosidebars#77]
When trying to activate woosidebars I get the following error

It is a new wordpress installation (5.6) in which I imported a template that requires woosidebars.
As soon as I want to activate the plugin, the page (and also the admin dashboard) is broken and only the following error is displayed

`Fatal error: Uncaught ValueError: Unknown format specifier "a" in C:\xampp\htdocs\project\wp-content\plugins\woosidebars\classes\class-woo-sidebars.php:170 Stack trace: #0 C:\xampp\htdocs\project\wp-content\plugins\woosidebars\classes\class-woo-sidebars.php(170): sprintf('Suche %a', 'Widget-Bereiche') #1 C:\xampp\htdocs\project\wp-includes\class-wp-hook.php(287): Woo_Sidebars->register_post_type('') #2 C:\xampp\htdocs\project\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\project\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\project\wp-settings.php(557): do_action('init') #5 C:\xampp\htdocs\project\wp-config.php(116): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\project\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\project\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\project\wp-admin\plugins.php(10): require_once('C:\\xampp\\htdocs...') #9 {main} thrown in C:\xampp\htdocs\project\wp-content\plugins\woosidebars\classes\class-woo-sidebars.php on line 170`

**Comment by DeveloperWil** [comment]
I am getting this error as well but only under PHP 8.0.0 NTS on local Windows 10 machine.

PHP Fatal error:  Uncaught ValueError: Unknown format specifier "a" in D:\Users\Wil\Dropbox\Projects\bitbucket\blahblah\www\wp-content\plugins\woosidebars\classes\class-woo-sidebars.php:170
